# Generated by Django 5.2.13 on 2026-04-18 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_platform', '0002_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubmissionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('love', 'Love')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='my_platform.submission')),
            ],
            options={
                'unique_together': {('submission', 'user_name')},
            },
        ),
    ]
